### ISSUE TITLE
Mixed Reality Headset Support

### ISSUE THREAD

**Issue by alanrenouf** [vmware/vr-dc-ex#7]
Add support for Mixed Reality headsets please

**Comment by neoof86** [comment]
I now have this working and done a guide like the Oculus over here http://vexpert.me/VRMR hope it helps!

**Comment by alanrenouf** [comment]
Thanks @neoof86 I tried it on my Dell Mixed Reality Headset and it does indeed work, the key is having the Mixed Reality Steam plugin installed (http://store.steampowered.com/app/719950/Windows_Mixed_Reality_for_SteamVR/) after that it kicked in and worked as expected.
